### ISSUE TITLE
Readme & Wiki Updates F3 3-4-0

### ISSUE THREAD

**Issue by Wolfenswan** [ferstaberinde/F3#687]
***Readme***

- Improved: Assign Gear AI now supports Syndikat etc.
- Improved: Pilots can now repair vehicles.
- Improved: Added new and update Polish translations of many terms
- Improved: Changed OrBat to Folk ARPS 2015 Orbat
- Improved: Ranks of pre-placed units adjusted to allow correct leadership when merging groups
- Improved: Separation of Vehicle gear script v2 #733
- Improved: TFR fix & radio designation changes #688
- Improved: Added Syndikat to pre-placed platoons component
- Improved: Added Syndikat support to Briefings component
- Improved: Added Syndikat support to Group IDs component
- Improved: Added Syndikat support to Group Markers component
- Improved: Added Syndikat support to Assign Gear component
- Improved: Added Syndikat support to Insignia component
- Improved: Group markers and Group ID systems made 3DEN-friendly (see #724)
- Improved: Changes to mission conditions #719
- Improved: fn_setAISkill now exits without an error message if AI skills are not set
- Improved: JTAC CAS elements now virtual
- Improved: Move CfgFunctions F3 definitions into its own hpp file. #643 (RE-WORD THIS)
- Improved: Moved settings from description.ext to in-editor #703  (RE-WORD THIS)
- Improved: Updates ORBAT to FAXORBAT 2015 standards (RE-WORD THIS)
- Improved: Fix spectator jumping on keyboard input and insignia error #710
- Improved: Updated F3 muting component #702
- Improved: Added support for defaulting ACRE2 radios to a starting channel
- Improved: Added "Use mission settings" option to mission conditions parameter
- Improved: Pre-Placed ZEUS units assign F3 AI Skill to created units
- Optimisations: ACRE2, setGroupID, Insignia
- Optimisation: Parameter system now works in singleplayer editor and has been made slightly faster
- Fixed: SWS would on occasion not properly immobilise downed players
- Removed: UAV recharge component
- Removed: ACRE1 support #711 (RE-WORD THIS)
- Removed: Modules for the pre-mount
- Removed: Reserved for JIP groups from  pre-placed platoons component

***Wiki***
- [x] ACRE2 channel defaulting, Removed: ACRE1 support #711, TFR fix & radio designation changes #688
- [x] Mission conditions component - new "use mission settings" option, Mission conditions selector (see #719)
- [x] Updated F3 muting component #702 
- [x] Pre-placed platoons component (added Syndikat), removed JIP groups
- [x] Pre-mount logics removed (but component remains)
- [x] Group Markers (see #724)
- [x] Group IDs (see #724)
- [ ] AssignGear component (Separation of Vehicle gear script v2 #733)
- [ ] Instructions for naming missions, adding author etc.
- [x] Briefing template
- [x] Insignia
- [x] Assign Gear AI (addresses #740, changed factions array to an exclude (i.e. unless specified all factions are processed) by default, non-recognized units now keep their default gear, added Syndikat units)

Plus add in (to above):

Reworked assignGear function: all if checks now compare the faction to an array of possible factions instead of a single comparison strings such as "aaf", "nato" etc. can now be used when forcing a specific faction loadout (instead of having to use the precise faction string, such as "ind_f")

Reword groupMarker component: changed switch structure to several if-checks. Benefit: Easier to show the same marker to several units/factions (you only need to add a single string instead of copying the entire block of code) NATO & CSAT (Pacific) are shown the default GrpNATO/GrpCSAT markers

Updated briefing.sqf: all if checks now compare the faction to an array of possible factions instead of a single comparison NATO & CSAT (Pacific) are both referred to the regular briefing_nato/_csat.sqf

***Credits***
- Wolfenswan 
- Ferrard Carson
- GeEom
- Snipers 
- JonBons
- Pasrules
- SuicideKing
- Przemro 
- darkChozo
- boarnoah
- Fer

**Comment by Wolfenswan** [comment]
* Done assign gear AI
* Fixed FA Platoons (was still refering to GrpVar = group this)
* Added ctrg to briefing
* Removed link to UAV charge

I **think** Group Markers & Group ID don't need any update.
